<?php

declare(strict_types=1);

namespace App\GraphQL\Types;

use Rebing\GraphQL\Support\Type as GraphQLType;
use GraphQL\Type\Definition\Type;
class ResultadoAnalisisType extends GraphQLType
{
    protected $attributes = [
        'name' => 'Resultado analisis Type'        
    ];

    public function fields(): array
    {
        return [
            'id'=>[
                'type'=>Type::nonNull(Type::int()),
                'description'=>'Invoice id'
            ],      
            'participacion_cuota_titular'=>[
                'type'=>Type::float(),
                'description'=>'participacion_cuota_titular'
            ],
            'participacion_cuota_total'=>[
                'type'=>Type::float(),
                'description'=>'participacion_cuota_total'
            ],
            'participacion_cuota_validacion'=>[
                'type'=>Type::float(),
                'description'=>'participacion_cuota_validacion'
            ],
            'resultado_eva'=>[
                'type'=>Type::string(),
                'description'=>'resultado_eva'
            ],
            'resultado_sist'=>[
                'type'=>Type::string(),
                'description'=>'resultado_sist'
            ],
            'ratios_endeudamiento'=>[
                'type'=>Type::float(),
                'description'=>'ratios_endeudamiento'
            ],
            'ratios_endeudamiento_resultado'=>[
                'type'=>Type::string(),
                'description'=>'ratios_endeudamiento_resultado'
            ],
            'ratios_margen_neto'=>[
                'type'=>Type::float(),
                'description'=>'ratios_margen_neto'
            ],
            'ratios_margen_neto_resultado'=>[
                'type'=>Type::string(),
                'description'=>'ratios_margen_neto_resultado'
            ],
            'ratios_liquidez'=>[
                'type'=>Type::float(),
                'description'=>'ratios_liquidez'
            ],
            'ratios_liquidez_resultado'=>[
                'type'=>Type::string(),
                'description'=>'ratios_liquidez_resultado'
            ],
            'ratios_solvencia'=>[
                'type'=>Type::float(),
                'description'=>'ratios_solvencia'
            ],
            'ratios_solvencia_resultado'=>[
                'type'=>Type::string(),
                'description'=>'ratios_solvencia_resultado'
            ],
            'ingresos_ventas_titular'=>[
                'type'=>Type::float(),
                'description'=>'ingresos_ventas_titular'
            ],
            'ingresos_ventas_conyuge'=>[
                'type'=>Type::float(),
                'description'=>'ingresos_ventas_conyuge'
            ],
            'ingresos_ventas_total'=>[
                'type'=>Type::float(),
                'description'=>'ingresos_ventas_total'
            ],
            'ingresos_ventas_validacion'=>[
                'type'=>Type::float(),
                'description'=>'ingresos_ventas_validacion'
            ],
            'costo_venta_titular'=>[
                'type'=>Type::float(),
                'description'=>'costo_venta_titular'
            ],
            'costo_venta_conyuge'=>[
                'type'=>Type::float(),
                'description'=>'costo_venta_conyuge'
            ],
            'costo_venta_total'=>[
                'type'=>Type::float(),
                'description'=>'costo_venta_total'
            ],
            'costo_venta_validacion'=>[
                'type'=>Type::float(),
                'description'=>'costo_venta_validacion'
            ],
            'margen_bruto_titular'=>[
                'type'=>Type::float(),
                'description'=>'margen_bruto_titular'
            ],
            'margen_bruto_conyuge'=>[
                'type'=>Type::float(),
                'description'=>'margen_bruto_conyuge'
            ],
            'margen_bruto_total'=>[
                'type'=>Type::float(),
                'description'=>'margen_bruto_total'
            ],
            'margen_bruto_validacion'=>[
                'type'=>Type::float(),
                'description'=>'margen_bruto_validacion'
            ],
            'otros_ingresos_titular'=>[
                'type'=>Type::float(),
                'description'=>'otros_ingresos_titular'
            ],
            'otros_ingresos_conyuge'=>[
                'type'=>Type::float(),
                'description'=>'otros_ingresos_conyuge'
            ],
            'otros_ingresos_total'=>[
                'type'=>Type::float(),
                'description'=>'otros_ingresos_total'
            ],
            'otros_ingresos_validacion'=>[
                'type'=>Type::float(),
                'description'=>'otros_ingresos_validacion'
            ],
            'servicios_lat_titular'=>[
                'type'=>Type::float(),
                'description'=>'servicios_lat_titular'
            ],
            'servicios_lat_conyuge'=>[
                'type'=>Type::float(),
                'description'=>'servicios_lat_conyuge'
            ],
            'servicios_lat_total'=>[
                'type'=>Type::float(),
                'description'=>'servicios_lat_total'
            ],
            'servicios_lat_validacion'=>[
                'type'=>Type::float(),
                'description'=>'servicios_lat_validacion'
            ],
            'alquiler_titular'=>[
                'type'=>Type::float(),
                'description'=>'alquiler_titular'
            ],
            'alquiler_conyuge'=>[
                'type'=>Type::float(),
                'description'=>'alquiler_conyuge'
            ],
            'alquiler_total'=>[
                'type'=>Type::float(),
                'description'=>'alquiler_total'
            ],
            'alquiler_validacion'=>[
                'type'=>Type::float(),
                'description'=>'alquiler_validacion'
            ],
            'empleados_titular'=>[
                'type'=>Type::float(),
                'description'=>'empleados_titular'
            ],
            'empleados_conyuge'=>[
                'type'=>Type::float(),
                'description'=>'empleados_conyuge'
            ],
            'empleados_total'=>[
                'type'=>Type::float(),
                'description'=>'empleados_total'
            ],
            'empleados_validacion'=>[
                'type'=>Type::float(),
                'description'=>'empleados_validacion'
            ],
            'gasto_financiero_titular'=>[
                'type'=>Type::float(),
                'description'=>'gasto_financiero_titular'
            ],
            'gasto_financiero_conyuge'=>[
                'type'=>Type::float(),
                'description'=>'gasto_financiero_conyuge'
            ],
            'gasto_financiero_total'=>[
                'type'=>Type::float(),
                'description'=>'gasto_financiero_total'
            ],
            'gasto_financiero_validacion'=>[
                'type'=>Type::float(),
                'description'=>'gasto_financiero_validacion'
            ],
            'gasto_hogar_titular'=>[
                'type'=>Type::float(),
                'description'=>'gasto_hogar_titular'
            ],
            'gasto_hogar_conyuge'=>[
                'type'=>Type::float(),
                'description'=>'gasto_hogar_conyuge'
            ],
            'gasto_hogar_total'=>[
                'type'=>Type::float(),
                'description'=>'gasto_hogar_total'
            ],
            'gasto_hogar_validacion'=>[
                'type'=>Type::float(),
                'description'=>'gasto_hogar_validacion'
            ],
            'gasto_financiero_personal_titular'=>[
                'type'=>Type::float(),
                'description'=>'gasto_financiero_personal_titular'
            ],
            'gasto_financiero_personal_conyuge'=>[
                'type'=>Type::float(),
                'description'=>'gasto_financiero_personal_conyuge'
            ],
            'gasto_financiero_personal_total'=>[
                'type'=>Type::float(),
                'description'=>'gasto_financiero_personal_total'
            ],
            'gasto_financiero_personal_validacion'=>[
                'type'=>Type::float(),
                'description'=>'gasto_financiero_personal_validacion'
            ],
            'cuota_institucion_titular'=>[
                'type'=>Type::float(),
                'description'=>'cuota_institucion_titular'
            ],
            'cuota_institucion_conyuge'=>[
                'type'=>Type::float(),
                'description'=>'cuota_institucion_conyuge'
            ],
            'cuota_institucion_total'=>[
                'type'=>Type::float(),
                'description'=>'cuota_institucion_total'
            ],
            'cuota_institucion_validacion'=>[
                'type'=>Type::float(),
                'description'=>'cuota_institucion_validacion'
            ],
            'utilidad_desp_cuota_titular'=>[
                'type'=>Type::float(),
                'description'=>'utilidad_desp_cuota_titular'
            ],
            'utilidad_desp_cuota_conyuge'=>[
                'type'=>Type::float(),
                'description'=>'utilidad_desp_cuota_conyuge'
            ],
            'utilidad_desp_cuota_total'=>[
                'type'=>Type::float(),
                'description'=>'utilidad_desp_cuota_total'
            ],
            'utilidad_desp_cuota_validacion'=>[
                'type'=>Type::float(),
                'description'=>'utilidad_desp_cuota_validacion'
            ],
            'balance_activo_caja'=>[
                'type'=>Type::float(),
                'description'=>'balance_activo_caja'
            ],
            'balance_activo_inventario'=>[
                'type'=>Type::float(),
                'description'=>'balance_activo_inventario'
            ],
            'balance_activo_f'=>[
                'type'=>Type::float(),
                'description'=>'balance_activo_f'
            ],
            'balance_activo_total'=>[
                'type'=>Type::float(),
                'description'=>'balance_activo_total'
            ],
            'balance_pasivo_deudas'=>[
                'type'=>Type::float(),
                'description'=>'balance_pasivo_deudas'
            ],
            'balance_patrimonio_capital'=>[
                'type'=>Type::float(),
                'description'=>'balance_patrimonio_capital'
            ],
            'balance_patrimonio_utilidad'=>[
                'type'=>Type::float(),
                'description'=>'balance_patrimonio_utilidad'
            ],
            'balance_patrimonio_total'=>[
                'type'=>Type::float(),
                'description'=>'balance_patrimonio_total'
            ],
            'fc_diario_minimo_ingreso'=>[
                'type'=>Type::float(),
                'description'=>'fc_diario_minimo_ingreso'
            ],
            'fc_diario_cuota'=>[
                'type'=>Type::float(),
                'description'=>'fc_diario_cuota'
            ],
            'fc_diario_disponible_diario'=>[
                'type'=>Type::float(),
                'description'=>'fc_diario_disponible_diario'
            ],
            'fc_diario_participacion_cuota'=>[
                'type'=>Type::float(),
                'description'=>'fc_diario_participacion_cuota'
            ],
            'fc_diario_resultado'=>[
                'type'=>Type::float(),
                'description'=>'fc_diario_resultado'
            ],
            'fc_semanal_minimo_ingreso'=>[
                'type'=>Type::float(),
                'description'=>'fc_semanal_minimo_ingreso'
            ],
            'fc_semanal_cuota'=>[
                'type'=>Type::float(),
                'description'=>'fc_semanal_cuota'
            ],
            'fc_semanal_participacion_cuota'=>[
                'type'=>Type::float(),
                'description'=>'fc_semanal_participacion_cuota'
            ],
            'fc_semanal_resultado'=>[
                'type'=>Type::float(),
                'description'=>'fc_semanal_resultado'
            ],
            'fc_semanal_disponible_semana'=>[
                'type'=>Type::float(),
                'description'=>'fc_semanal_disponible_semana'
            ],
            'utilidad_neta_negocio_titular'=>[
                'type'=>Type::float(),
                'description'=>'utilidad_neta_negocio_titular'
            ],
            'utilidad_neta_negocio_conyuge'=>[
                'type'=>Type::float(),
                'description'=>'utilidad_neta_negocio_conyuge'
            ],
            'utilidad_neta_negocio_total'=>[
                'type'=>Type::float(),
                'description'=>'utilidad_neta_negocio_total'
            ],
            'utilidad_neta_negocio_validacion'=>[
                'type'=>Type::float(),
                'description'=>'utilidad_neta_negocio_validacion'
            ],
            'disponible_titular'=>[
                'type'=>Type::float(),
                'description'=>'disponible_titular'
            ],
            'disponible_conyuge'=>[
                'type'=>Type::float(),
                'description'=>'disponible_conyuge'
            ],
            'disponible_total'=>[
                'type'=>Type::float(),
                'description'=>'disponible_total'
            ],
            'disponible_validacion'=>[
                'type'=>Type::float(),
                'description'=>'disponible_validacion'
            ],
        ];
    }
}
